### PR TITLE
Increase memory size for Nano X and Nano S+

### PR DESCRIPTION
**Pull request by volovyks**

### CODE REVIEW

**Comment by volovyks** [comment]
Any feedback on this? How should we proceed?

**Comment by kaifeur** [comment]
@volovyks have you checked this? https://developers.ledger.com/docs/embedded-app/maintenance/

**Comment by volovyks** [comment]
@kaifeur filled the form

**Comment by kaifeur** [comment]
I opened the original PR on Aug 21 2022 and the feature is still not on my Ledger yet :)
@jibeee, @sgliner-ledger or @xchapron-ledger could you help with this one?

**Comment by xchapron-ledger** [comment]
> I opened the original PR on Aug 21 2022 and the feature is still not on my Ledger yet :) @jibeee, @sgliner-ledger or @xchapron-ledger could you help with this one?

Sorry for the late reply.
We will have a look into this soon will working on some adaptation for Stax device.

**Comment by PierreLeGuen** [comment]
@xchapron-ledger, do you have any updates on this? It's a highly anticipated change within the NEAR ecosystem.

**Review by sgliner-ledger — APPROVED** [review]

**Comment by tdejoigny-ledger** [comment]
@volovyks @PierreLeGuen, did you test this code ? it seems that it's not working...
It seems that the issue is here :

```
  static int check_overflow(unsigned int processed, unsigned int size) {
      PRINTF("check_overflow %d %d %d\n", processed, size, tmp_ctx.signing_context.buffer_used);
      if (size > tmp_ctx.signing_context.buffer_used || processed + size > tmp_ctx.signing_context.buffer_used) {
          return SIGN_PARSING_ERROR;
      }
      return 0;
  }
```

Always return `SIGN_PARSING_ERROR`

**Pull request merged**
